// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azutcgzxojrzsguleszm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dXRjZ3p4b2pyenNndWxlc3ptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MTQ1NDgsImV4cCI6MjA2MDI5MDU0OH0.5FAt40JBTi4wvtEcCirI0DCVJb3KvGnpYl6K7nct4YY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});